var jsexports = { js: {} };
jsexports['js']['(v, i, x) => v[i] = x'] = (v, i, x) => v[i] = x;
jsexports['js']['(x) => Math.log2(x)'] = (x) => Math.log2(x);
jsexports['js']['(x) => (new TextDecoder()).decode(x)'] = (x) => (new TextDecoder()).decode(x);
jsexports['js']['(x,sep) => x.join(sep)'] = (x,sep) => x.join(sep);
jsexports['js']['x => mdpad[x]'] = x => mdpad[x];
jsexports['js']['(x) => console.log(x)'] = (x) => console.log(x);
jsexports['js']['n => Array(n)'] = n => Array(n);
jsexports['js']['n => new Float64Array(n)'] = n => new Float64Array(n);
jsexports['js']['(x) => Math.sign(x)'] = (x) => Math.sign(x);
jsexports['js']['n => new Uint8Array(n)'] = n => new Uint8Array(n);
jsexports['js']['(id, data, layout, config) => Plotly.newPlot(id, data, layout, config)'] = (id, data, layout, config) => Plotly.newPlot(id, data, layout, config);
jsexports['js']['() => ({})'] = () => ({});