input = """

hello

````@example basics
using WebAssemblyCompiler #hideall
const h = JS.h

function basics(x)
    n = h("p",
          h("strong", " This is strong text with a class."), class = "myclass")
    n = h("div", "This is some text generated by `JS.h`. ",
          "This is a number: ", x, n, class = "myclass2")
    JS.sethtml("myid", string(n))
    JS.eval("alert('Generated by Julia')")
    JS.console_log((arr = [1., 2., 3.], str = "hello", num = 2.0, tp = (3, 3.)))
    return x
end
nothing #hide
````

Compile it using:

````@example basics
compile((basics, Float64); filepath = "basics/basics.wasm", validate = true, optimize = false)
````
"""



function hideall(input)
    lines = split(input, "\n")
    inexample = false
    shouldhide = false
    for (i,s) in enumerate(lines)
        if occursin(r"^````@example", s)
            inexample = true
        end
        if inexample && occursin(r"\#hideall", s)
            shouldhide = true
        end
        if occursin(r"^````", s) && !occursin("@", s)
            inexample = false
            shouldhide = false
        end
        if inexample && shouldhide
            lines[i] *= "   #hide"
        end
        @show i s inexample shouldhide
    end
    return join(lines, "\n")
end

print(hideall(input))
