var jsexports = { js: {} };
jsexports['js']['(v, i, x) => v[i] = x'] = (v, i, x) => v[i] = x;
jsexports['js']['(x) => (new TextDecoder()).decode(x)'] = (x) => (new TextDecoder()).decode(x);
jsexports['js']['(x,sep) => x.join(sep)'] = (x,sep) => x.join(sep);
jsexports['js']['(x, str) => x.innerHTML = str'] = (x, str) => x.innerHTML = str;
jsexports['js']['(x) => console.log(x)'] = (x) => console.log(x);
jsexports['js']['n => Array(n)'] = n => Array(n);
jsexports['js']['(x) => document.getElementById(x)'] = (x) => document.getElementById(x);
jsexports['js']['(x) => Math.sin(x)'] = (x) => Math.sin(x);
jsexports['js']['n => new Uint8Array(n)'] = n => new Uint8Array(n);